# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/sample-api.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./redoc/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
