# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  sample: openapi/sample-api.yaml
  closet: openapi/closet.yaml
  # fancy: openapi/fancy.yaml  # openapi v3
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./redoc/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
